/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface Contact {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'message' : string,
  'phone' : string,
}
export interface Job {
  'id' : bigint,
  'deleted' : boolean,
  'postedBy' : string,
  'createdAt' : bigint,
  'description' : string,
  'approved' : boolean,
  'category' : string,
  'payOffered' : string,
  'location' : string,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'message' : string,
}
export interface Worker {
  'id' : bigint,
  'expectedSalary' : string,
  'blocked' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'experience' : string,
  'approved' : boolean,
  'category' : string,
  'location' : string,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[string], undefined>,
  'adminUpdateJob' : ActorMethod<
    [bigint, string, string, string, string, string],
    boolean
  >,
  'adminUpdateWorker' : ActorMethod<
    [bigint, string, string, string, string, string],
    boolean
  >,
  'approveJob' : ActorMethod<[bigint], boolean>,
  'approveWorker' : ActorMethod<[bigint], boolean>,
  'blockWorker' : ActorMethod<[bigint], boolean>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'checkAdminCredentials' : ActorMethod<[string, string], boolean>,
  'checkAdminPassword' : ActorMethod<[string], boolean>,
  'resetAdminToDefault' : ActorMethod<[], undefined>,
  'createJob' : ActorMethod<[string, string, string, string, string], Job>,
  'createJobApproved' : ActorMethod<[string, string, string, string, string], Job>,
  'createWorker' : ActorMethod<
    [string, string, string, string, string],
    Worker
  >,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteJob' : ActorMethod<[bigint], boolean>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getAppContent' : ActorMethod<
    [],
    {
      'supportDetails' : string,
      'homeText' : string,
      'bannerText' : string,
      'announcement' : string,
      'contactNumber' : string,
    }
  >,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getJobsByCategory' : ActorMethod<[string], Array<Job>>,
  'getJobsByLocation' : ActorMethod<[string], Array<Job>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getWorkersByCategory' : ActorMethod<[string], Array<Worker>>,
  'getWorkersByLocation' : ActorMethod<[string], Array<Worker>>,
  'seed' : ActorMethod<[], undefined>,
  'sendNotification' : ActorMethod<[string, string], undefined>,
  'submitContact' : ActorMethod<[string, string, string], Contact>,
  'unblockWorker' : ActorMethod<[bigint], boolean>,
  'updateAppContent' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateCategory' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];