/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Job = IDL.Record({
  'id' : IDL.Nat,
  'deleted' : IDL.Bool,
  'postedBy' : IDL.Text,
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'approved' : IDL.Bool,
  'category' : IDL.Text,
  'payOffered' : IDL.Text,
  'location' : IDL.Text,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'expectedSalary' : IDL.Text,
  'blocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'experience' : IDL.Text,
  'approved' : IDL.Bool,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'adminUpdateJob' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminUpdateWorker' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'approveJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'approveWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'blockWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Job],
      [],
    ),
  'createWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Worker],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getAppContent' : IDL.Func(
      [],
      [
        IDL.Record({
          'supportDetails' : IDL.Text,
          'homeText' : IDL.Text,
          'bannerText' : IDL.Text,
          'announcement' : IDL.Text,
          'contactNumber' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getJobsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getWorkersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'getWorkersByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'seed' : IDL.Func([], [], []),
  'sendNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Contact], []),
  'unblockWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateAppContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'deleted' : IDL.Bool,
    'postedBy' : IDL.Text,
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'approved' : IDL.Bool,
    'category' : IDL.Text,
    'payOffered' : IDL.Text,
    'location' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'expectedSalary' : IDL.Text,
    'blocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'experience' : IDL.Text,
    'approved' : IDL.Bool,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'adminUpdateJob' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminUpdateWorker' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'approveJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'approveWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'blockWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Job],
        [],
      ),
    'createWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Worker],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getAppContent' : IDL.Func(
        [],
        [
          IDL.Record({
            'supportDetails' : IDL.Text,
            'homeText' : IDL.Text,
            'bannerText' : IDL.Text,
            'announcement' : IDL.Text,
            'contactNumber' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getJobsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getWorkersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'getWorkersByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'seed' : IDL.Func([], [], []),
    'sendNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Contact], []),
    'unblockWorker' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateAppContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };