/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: bigint;
    name: string;
}
export interface Job {
    id: bigint;
    deleted: boolean;
    postedBy: string;
    createdAt: bigint;
    description: string;
    approved: boolean;
    category: string;
    payOffered: string;
    location: string;
}
export interface Worker {
    id: bigint;
    expectedSalary: string;
    blocked: boolean;
    name: string;
    createdAt: bigint;
    experience: string;
    approved: boolean;
    category: string;
    location: string;
}
export interface Notification {
    id: bigint;
    title: string;
    createdAt: bigint;
    message: string;
}
export interface Contact {
    id: bigint;
    name: string;
    createdAt: bigint;
    message: string;
    phone: string;
}
export interface backendInterface {
    addCategory(name: string): Promise<void>;
    adminUpdateJob(id: bigint, category: string, location: string, description: string, payOffered: string, postedBy: string): Promise<boolean>;
    adminUpdateWorker(id: bigint, name: string, experience: string, location: string, expectedSalary: string, category: string): Promise<boolean>;
    approveJob(id: bigint): Promise<boolean>;
    approveWorker(id: bigint): Promise<boolean>;
    blockWorker(id: bigint): Promise<boolean>;
    changeAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    checkAdminCredentials(username: string, password: string): Promise<boolean>;
    checkAdminPassword(password: string): Promise<boolean>;
    changeAdminCredentials(oldPassword: string, newUsername: string, newPassword: string): Promise<boolean>;
    resetAdminToDefault(): Promise<void>;
    createJob(category: string, location: string, description: string, payOffered: string, postedBy: string): Promise<Job>;
    createWorker(name: string, experience: string, location: string, expectedSalary: string, category: string): Promise<Worker>;
    deleteCategory(id: bigint): Promise<boolean>;
    deleteJob(id: bigint): Promise<boolean>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllJobs(): Promise<Array<Job>>;
    getAllWorkers(): Promise<Array<Worker>>;
    getAppContent(): Promise<{
        supportDetails: string;
        homeText: string;
        bannerText: string;
        announcement: string;
        contactNumber: string;
    }>;
    getCategories(): Promise<Array<Category>>;
    getJobsByCategory(category: string): Promise<Array<Job>>;
    getJobsByLocation(location: string): Promise<Array<Job>>;
    getNotifications(): Promise<Array<Notification>>;
    getWorkersByCategory(category: string): Promise<Array<Worker>>;
    getWorkersByLocation(location: string): Promise<Array<Worker>>;
    seed(): Promise<void>;
    sendNotification(title: string, message: string): Promise<void>;
    submitContact(name: string, phone: string, message: string): Promise<Contact>;
    unblockWorker(id: bigint): Promise<boolean>;
    updateAppContent(homeText: string, bannerText: string, announcement: string, contactNumber: string, supportDetails: string): Promise<void>;
    updateCategory(id: bigint, name: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async adminUpdateJob(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateJob(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateJob(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async adminUpdateWorker(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveJob(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJob(arg0);
            return result;
        }
    }
    async approveWorker(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWorker(arg0);
            return result;
        }
    }
    async blockWorker(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.blockWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockWorker(arg0);
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async checkAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdminPassword(arg0);
            return result;
        }
    }
    async checkAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).checkAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).checkAdminCredentials(arg0, arg1);
            return result;
        }
    }
    async changeAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).changeAdminCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).changeAdminCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async resetAdminToDefault(): Promise<void> {
        if (this.processError) {
            try {
                await (this.actor as any).resetAdminToDefault();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await (this.actor as any).resetAdminToDefault();
        }
    }
    async createJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createWorker(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Worker> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorker(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorker(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return result;
        }
    }
    async getAllWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkers();
            return result;
        }
    }
    async getAppContent(): Promise<{
        supportDetails: string;
        homeText: string;
        bannerText: string;
        announcement: string;
        contactNumber: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppContent();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getJobsByCategory(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCategory(arg0);
            return result;
        }
    }
    async getJobsByLocation(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByLocation(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getWorkersByCategory(arg0: string): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkersByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkersByCategory(arg0);
            return result;
        }
    }
    async getWorkersByLocation(arg0: string): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkersByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkersByLocation(arg0);
            return result;
        }
    }
    async seed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seed();
            return result;
        }
    }
    async sendNotification(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return result;
        }
    }
    async unblockWorker(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockWorker(arg0);
            return result;
        }
    }
    async updateAppContent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppContent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppContent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
